services:
  - type: web
    name: yajus-kitchen
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python run_migrations.py"
    startCommand: "gunicorn yajus_kitchen.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: TIDB_HOST
        sync: false
      - key: TIDB_PORT
        sync: false
      - key: TIDB_USER
        sync: false
      - key: TIDB_PASSWORD
        sync: false
      - key: TIDB_DB_NAME
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_WEBHOOK_SECRET
        sync: false