# Generated by Django 6.0.1 on 2026-06-27 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current available stock'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='Enable automatic stock tracking'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['name'], name='kitchen_foo_name_91083f_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['category'], name='kitchen_foo_categor_28d06b_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['is_available'], name='kitchen_foo_is_avai_5aabd9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='kitchen_ord_status_c5bdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='kitchen_ord_created_bb3737_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='kitchen_ord_user_id_f95b68_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='kitchen_ord_email_7bc824_idx'),
        ),
    ]
